# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfb44fae68ac433c4926aa4e8d36c58174833594d3403bbbfc292c1cd12d6d74e675ca02bde97fdc3a64d1529317ef05fe5ca62e86f1d8663335d219bfdfcc83

test:
  secret_key_base: 1bdc49c9294a50a63ad337c3c02e9f5c7663679c28fd085da9569f2c8ad25d4076da2f09f52e6cdcef797d86d398d00b9484dd578d60955f8cc82e37be15690a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
